name: CI/CD

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
   # ===========================================
   # Validate: Lint and Test affected projects
   # ===========================================
   validate:
      name: Validate
      runs-on: ubuntu-latest
      permissions:
         actions: read
         contents: read
         checks: write
         pull-requests: write
      steps:
         - name: Checkout
           uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - name: Setup pnpm
           uses: pnpm/action-setup@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 20
              cache: 'pnpm'

         - name: Install dependencies
           run: pnpm install --frozen-lockfile

         - name: Set Nx base SHA
           uses: nrwl/nx-set-shas@v4
           if: github.event_name == 'pull_request'

         - name: Lint affected projects (PR)
           if: github.event_name == 'pull_request'
           run: pnpm affected:lint
           continue-on-error: true

         - name: Lint all projects (main)
           if: github.event_name == 'push'
           run: pnpm lint
           continue-on-error: true

         - name: Test affected projects with coverage (PR)
           if: github.event_name == 'pull_request'
           run: pnpm nx affected -t test -- --reporter=default --reporter=junit --outputFile=test-results.xml --coverage --coverage.reporter=lcov --coverage.reporter=json --coverage.reporter=json-summary --coverage.reporter=text-summary

         - name: Test all projects with coverage (main)
           if: github.event_name == 'push'
           run: pnpm test -- --reporter=default --reporter=junit --outputFile=test-results.xml --coverage --coverage.reporter=lcov --coverage.reporter=json --coverage.reporter=json-summary --coverage.reporter=text-summary

         - name: Merge coverage reports
           if: always()
           run: |
              mkdir -p coverage
              find . -name "lcov.info" -path "*/coverage/*" | head -20 | xargs -I {} cat {} >> coverage/lcov.info || true

         - name: Test Report
           uses: dorny/test-reporter@v1
           if: always()
           with:
              name: Test Results
              path: '**/test-results.xml'
              reporter: jest-junit
              fail-on-error: true
              fail-on-empty: false

         # Add coverage report steps per app as needed:
         # - name: Coverage Report - Portal
         #   uses: davelosert/vitest-coverage-report-action@v2
         #   if: always() && github.event_name == 'pull_request'
         #   with:
         #      json-summary-path: './apps/portal/coverage/coverage-summary.json'
         #      json-final-path: './apps/portal/coverage/coverage-final.json'
         #      vite-config-path: './vitest.workspace.ts'
         #      name: 'Portal'
         #   continue-on-error: true

   # ===========================================
   # Supabase Deploy (Migrations + Edge Functions)
   # Must run BEFORE frontend deployments
   # ===========================================
   supabase-deploy:
      name: Deploy Supabase (Migrations + Functions)
      needs: [validate]
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      environment:
         name: production
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup Supabase CLI
           uses: supabase/setup-cli@v1
           with:
              version: latest

         - name: Link Supabase project
           run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
           env:
              SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

         - name: Apply database migrations
           run: supabase db push
           env:
              SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

         - name: Deploy Edge Functions
           run: supabase functions deploy
           env:
              SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

   # ===========================================
   # Frontend Production Deployments
   # ===========================================

   # -----------------------------------------
   # Portal (Admin App)
   # -----------------------------------------
   production-portal:
      name: Deploy Portal to Production
      needs: [validate, supabase-deploy]
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      environment:
         name: production
         url: ${{ steps.deploy.outputs.url }}
      env:
         VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
         VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PORTAL_PROJECT_ID }}
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup pnpm
           uses: pnpm/action-setup@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 20
              cache: 'pnpm'

         - name: Install dependencies
           run: pnpm install --frozen-lockfile

         # Build with Nx to avoid Vercel CLI monorepo path issues
         - name: Build with Nx
           run: pnpm nx build @<org>/portal
           env:
              NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
              NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
              # Add other env vars as needed:
              # NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}

         # Create .vercel/output at REPO ROOT for prebuilt deployment
         - name: Prepare Vercel Build Output
           run: |
              mkdir -p .vercel/output/static
              cp -r apps/portal/dist/* .vercel/output/static/
              cat > .vercel/output/config.json << 'EOF'
              {
                "version": 3,
                "routes": [
                  { "handle": "filesystem" },
                  { "src": "/((?!assets/).*)", "dest": "/index.html" }
                ],
                "overrides": {},
                "headers": [
                  {
                    "source": "/(.*)",
                    "headers": [
                      {
                        "key": "Content-Security-Policy",
                        "value": "script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' *.supabase.co; frame-src 'self'; font-src 'self';"
                      }
                    ]
                  }
                ]
              }
              EOF

         - name: Deploy to Vercel Production
           id: deploy
           run: |
              URL=$(pnpm dlx vercel@latest deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
              echo "url=$URL" >> $GITHUB_OUTPUT

   # -----------------------------------------
   # Mobile App
   # -----------------------------------------
   production-app:
      name: Deploy App to Production
      needs: [validate, supabase-deploy]
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      environment:
         name: production
         url: ${{ steps.deploy.outputs.url }}
      env:
         VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
         VERCEL_PROJECT_ID: ${{ secrets.VERCEL_APP_PROJECT_ID }}
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup pnpm
           uses: pnpm/action-setup@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 20
              cache: 'pnpm'

         - name: Install dependencies
           run: pnpm install --frozen-lockfile

         - name: Build with Nx
           run: pnpm nx build @<org>/app
           env:
              NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
              NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

         - name: Prepare Vercel Build Output
           run: |
              mkdir -p .vercel/output/static
              cp -r apps/app/dist/* .vercel/output/static/
              cat > .vercel/output/config.json << 'EOF'
              {
                "version": 3,
                "routes": [
                  { "handle": "filesystem" },
                  { "src": "/((?!assets/).*)", "dest": "/index.html" }
                ],
                "overrides": {},
                "headers": [
                  {
                    "source": "/(.*)",
                    "headers": [
                      {
                        "key": "Content-Security-Policy",
                        "value": "script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' *.supabase.co; frame-src 'self'; font-src 'self';"
                      }
                    ]
                  }
                ]
              }
              EOF

         - name: Deploy to Vercel Production
           id: deploy
           run: |
              URL=$(pnpm dlx vercel@latest deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
              echo "url=$URL" >> $GITHUB_OUTPUT
